[tool.poetry]
name = "vector-db-benchmark"
version = "0.1.0"
description = ""
package-mode = false
authors = ["Kacper Łukawski <kacper.lukawski@qdrant.com>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.14"
typer = "^0.19.0"
jsons = "^1.6.3"
h5py = "^3.7.0"
redis = "^6.4.0"
ipdb = "^0.13.9"
stopit = "^1.1.2"
tqdm = "^4.66.1"
backoff = "^2.2.1"
ml-dtypes = "^0.4.0"
boto3 = "^1.39.4"
setuptools = "^80.9.0"
requests = "^2.32.5"


[tool.poetry.group.dev.dependencies]
pre-commit = "^2.20.0"
pytest = "^7.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
